import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <div className=" min-w-screen min-h-screen flex flex-col items-center justify-center">
      Contact
    </div>
  );
}
