import type { Metadata } from "next";
import Head from "next/head";
export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <div className=" min-w-screen min-h-screen flex flex-col  justify-center">
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Contact us for inquiries or support" />
      </Head>
      <div className="min-h-screen flex justify-center items-center py-12">
        <div className=" p-8 sm:p-10 md:w-3/6 md:p-12 lg:p-16 rounded-xl shadow-xl max-w-4xl w-full">
          <h1 className="text-4xl font-extrabold text-center mb-6">Contact Us</h1>
          <p className="text-center text-lg text-gray-600 mb-10">
            We’d love to hear from you! Please fill out the form below and we’ll get back to you as soon as possible.
          </p>

          <form action="#" method="POST" className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="name" className="block text-lg font-medium text-gray-700">Name</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  required
                  className="mt-2 p-3 w-full border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label htmlFor="email" className="block text-lg font-medium text-gray-700">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  required
                  className="mt-2 p-3 w-full border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>

            <div>
              <label htmlFor="message" className="block text-lg font-medium text-gray-700">Message</label>
              <textarea
                id="message"
                name="message"
                required
                className="mt-2 p-4 w-full border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              ></textarea>
            </div>

            <div className="flex justify-center">
              <button
                type="submit"
                className="w-full sm:w-auto bg-blue-600 text-white px-6 py-3 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-300"
              >
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
