import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};
export default function Project() {
  return (
    <div className=" min-w-screen min-h-screen flex flex-col items-center justify-center">
      Project
    </div>
  );
}
