import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "About me",
  description: "Generated by create next app",
};
export default function About() {
  return (
    <div className=" min-h-screen min-w-screen flex flex-col items-center justify-center">
      About
    </div>
  );
}
