import type { Metadata } from "next";
import Head from "next/head";
import Image from "next/image";
import Img from '../../../public/a-high-resolution-logo.png'
export const metadata: Metadata = {
  title: "About me",
  description: "Generated by create next app",
};
export default function About() {
  return (
    <div className=" min-h-screen min-w-screen flex flex-col items-center justify-center pt-7">
      <Head>
        <title className="">About Me</title>
        <meta name="description" content="Learn more about me" />
      </Head>

      <div className="min-h-screen flex items-center justify-center py-16">
        <div className="rounded-xl shadow-2xl max-w-4xl w-full p-8 md:p-12">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-extrabold text-gray-800 mb-4">About Me</h1>
            <p className="text-lg text-gray-600">A brief introduction about who I am and what I do.</p>
          </div>

          <div className="flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="flex-shrink-0">
              <Image
                src={Img} // Add your profile image here (adjust the path accordingly)
                height={500}
                width={500}
                alt="Profile Picture"
                className="w-40 h-40 rounded-full border-4 border-indigo-500 shadow-lg object-cover"
              />
            </div>

            <div className="flex flex-col items-center md:items-start">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">Hello! I'm Ashish</h2>
              <p className="text-lg text-gray-600 mb-6 text-center md:text-left">
                I’m a passionate developer with a love for coding, problem-solving, and learning new technologies.
                I specialize in web development and have experience building full-stack applications.
              </p>

              <div className="space-y-4 text-gray-700 mb-8">
                <h3 className="font-semibold text-xl">Key Skills:</h3>
                <ul className="list-disc pl-6">
                  <li>Frontend Development (React, Next.js, Tailwind CSS)</li>
                  <li>Backend Development (Node.js, Express, MongoDB,Typecript,Javascript)</li>
                  <li>Version Control (Git, GitHub)</li>
                  <li>Problem Solving and Algorithms</li>
                </ul>
              </div>

              <div className="space-y-4 text-gray-700">
                <h3 className="font-semibold text-xl">Hobbies & Interests:</h3>
                <ul className="list-disc pl-6">
                  <li>Coding and open-source contributions</li>
                  <li>Playing games like chess</li>
                  <li>Traveling and exploring new places</li>
                  <li>Reading books on technology and self-development</li>
                </ul>
              </div>

              <div className="mt-8">
                <a
                  href="mailto:kapoorashish714@gmail.com" // Replace with your email address
                  className="bg-indigo-600 text-white py-3 px-6 rounded-full hover:bg-indigo-700 transition duration-300"
                >
                  Get in Touch
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
